
COMB(esc_combo,			KC_ESC,			KC_W, KC_E)
COMB(grave_combo,		KC_GRAVE,		KC_E, KC_R)

COMB(ent_combo,			KC_ENT,			KC_D, KC_F)
COMB(tab_combo,			KC_TAB,			KC_S, KC_D)

COMB(lead_combo,		QK_LEAD,		KC_Q, MOD_P)

COMB(mins_combo,        KC_MINS,        KC_U, KC_I)
COMB(eql_combo,         KC_EQL,         KC_I, KC_O)


COMB(quote_combo,		KC_QUOT,		KC_L, KC_SCLN)
COMB(backslash_combo,	KC_BSLS,		KC_DOT, L_SLASH)


COMB(snake_case_combo,	C_SNAKECASE,	KC_F, KC_J)
COMB(snake_nav_combo,	C_NAVCASE,		KC_F, KC_J, KC_K)
COMB(ri_case_combo,		C_RI_CASE,		KC_R, KC_U)